import * as React from 'react';
import { useDataFactory } from '@/use-data-factory';
import { FlattenTreeTable } from '@/flatten-tree-table';

export default { component: FlattenTreeTable, title: 'demo/FlattenTreeTable',  };

const formatRows = [
  {
    id: 31274,
    name: '技术中台-服务器运营',
    level: 1,
    dataRowIndex: 1,
    defaultExpand: true,
    defaultDisplay: true,
    parent: null,
    unit: 1,
    numberStyle: 'FINANCE',
    format: '(0,0)',
    valueType: 'rowAndColumnCalculation',
    condition: null,
  },
  {
    id: 31275,
    name: '阿里巴巴-服务器费用-CTO',
    level: 2,
    dataRowIndex: 2,
    defaultExpand: true,
    defaultDisplay: true,
    parent: 1,
    unit: 1,
    numberStyle: 'FINANCE',
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31276,
    name: '阿里巴巴-其他运营-CTO',
    level: 2,
    dataRowIndex: 3,
    defaultExpand: true,
    defaultDisplay: true,
    parent: 1,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31277,
    name: '阿里巴巴-服务器费用-产品',
    level: 2,
    dataRowIndex: 4,
    defaultExpand: true,
    defaultDisplay: true,
    parent: 1,
    unit: null,
    numberStyle: 'FINANCE',
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31278,
    name: '阿里巴巴-其他运营-产品',
    level: 2,
    dataRowIndex: 5,
    defaultExpand: true,
    defaultDisplay: true,
    parent: 1,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 32044,
    name: '新维度7628',
    level: 1,
    dataRowIndex: 6,
    defaultExpand: true,
    defaultDisplay: true,
    parent: null,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'setNull',
    condition: null,
  },
];

const formatColumns = [
  {
    id: 31397,
    name: '本版预测',
    level: 1,
    dataColIndex: 'A',
    defaultExpand: true,
    defaultDisplay: true,
    parent: null,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'rowAndColumnCalculation',
    condition: null,
  },
  {
    id: 31322,
    name: 'Mar $数值类型',
    level: 2,
    dataColIndex: 'AA',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31629,
    name: '年度预算',
    level: 1,
    dataColIndex: 'AB',
    defaultExpand: true,
    defaultDisplay: true,
    parent: null,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'rowAndColumnCalculation',
    condition: null,
  },
  {
    id: 31329,
    name: 'Apr 预算',
    level: 2,
    dataColIndex: 'AC',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31330,
    name: 'May 预算',
    level: 2,
    dataColIndex: 'AD',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31331,
    name: 'Jun 预算',
    level: 2,
    dataColIndex: 'AE',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31332,
    name: 'Jul 预算',
    level: 2,
    dataColIndex: 'AF',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31334,
    name: 'Aug 预算',
    level: 2,
    dataColIndex: 'AG',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31333,
    name: 'Sep 预算',
    level: 2,
    dataColIndex: 'AH',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31335,
    name: 'Oct 预算',
    level: 2,
    dataColIndex: 'AI',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31336,
    name: 'Nov 预算',
    level: 2,
    dataColIndex: 'AJ',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31337,
    name: 'Dec 预算',
    level: 2,
    dataColIndex: 'AK',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31338,
    name: 'Jan 预算',
    level: 2,
    dataColIndex: 'AL',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31339,
    name: 'Feb 预算',
    level: 2,
    dataColIndex: 'AM',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31340,
    name: 'Mar 预算',
    level: 2,
    dataColIndex: 'AN',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'AB',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31279,
    name: 'April$数值类型',
    level: 2,
    dataColIndex: 'B',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: 1,
    numberStyle: null,
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31280,
    name: 'May$数值类型',
    level: 2,
    dataColIndex: 'C',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: 'FINANCE',
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31281,
    name: 'Jun$数值类型',
    level: 2,
    dataColIndex: 'D',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31301,
    name: 'Jul$数值类型',
    level: 2,
    dataColIndex: 'E',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: 1,
    numberStyle: null,
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31302,
    name: 'Aug$数值类型',
    level: 2,
    dataColIndex: 'F',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 32701,
    name: 'Aug$数值类型_copy_8541',
    level: 2,
    dataColIndex: 'G',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31303,
    name: 'Sep$数值类型',
    level: 2,
    dataColIndex: 'H',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: 1,
    numberStyle: null,
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31304,
    name: 'Oct$数值类型',
    level: 2,
    dataColIndex: 'I',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31305,
    name: 'Nov$数值类型',
    level: 2,
    dataColIndex: 'J',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31306,
    name: 'Dec$数值类型',
    level: 2,
    dataColIndex: 'K',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31307,
    name: 'Jan$数值类型',
    level: 2,
    dataColIndex: 'L',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31308,
    name: 'Feb$数值类型',
    level: 2,
    dataColIndex: 'M',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31309,
    name: 'Mar$数值类型',
    level: 2,
    dataColIndex: 'N',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'A',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31449,
    name: '上版本预测',
    level: 1,
    dataColIndex: 'O',
    defaultExpand: true,
    defaultDisplay: true,
    parent: null,
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'rowAndColumnCalculation',
    condition: null,
  },
  {
    id: 31310,
    name: 'April $数值类型',
    level: 2,
    dataColIndex: 'P',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31311,
    name: 'May $数值类型',
    level: 2,
    dataColIndex: 'Q',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31312,
    name: 'Jun $数值类型',
    level: 2,
    dataColIndex: 'R',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31313,
    name: 'Jul $数值类型',
    level: 2,
    dataColIndex: 'S',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31314,
    name: 'Aug $数值类型',
    level: 2,
    dataColIndex: 'T',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31315,
    name: 'Sep $数值类型',
    level: 2,
    dataColIndex: 'U',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31316,
    name: 'Oct $数值类型',
    level: 2,
    dataColIndex: 'V',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31317,
    name: 'Nev $数值类型',
    level: 2,
    dataColIndex: 'W',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31318,
    name: 'Dec $数值类型',
    level: 2,
    dataColIndex: 'X',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31320,
    name: 'Jan $数值类型',
    level: 2,
    dataColIndex: 'Y',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '',
    valueType: 'indicator',
    condition: null,
  },
  {
    id: 31321,
    name: 'Feb $数值类型',
    level: 2,
    dataColIndex: 'Z',
    defaultExpand: true,
    defaultDisplay: true,
    parent: 'O',
    unit: null,
    numberStyle: null,
    format: '(0,0)',
    valueType: 'indicator',
    condition: null,
  },
];

export const 折叠展示 = () => {
  const { tableProps, updateDS } = useDataFactory({
    mode: 'flattenTree',
    rowHeaders: formatRows,
    colHeaders: formatColumns,
  });

  React.useEffect(() => {
    setTimeout(() => {
      const dataList = [
        {
          columnIndex: 'AB',
          rowIndex: '1',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AC',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AD',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AG',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AA',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'AD',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AC',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AH',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AD',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AA',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'AB',
          rowIndex: '3',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AG',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AH',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AC',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AB',
          rowIndex: '2',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AA',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'AH',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AG',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AG',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AH',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AA',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'AB',
          rowIndex: '5',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AC',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AH',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AG',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AB',
          rowIndex: '4',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AA',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'AD',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AH',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AC',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AD',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AA',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'AG',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AF',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AE',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AD',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AC',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AB',
          rowIndex: '6',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'AJ',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AJ',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AJ',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AJ',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AJ',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AI',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AN',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AM',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AL',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AK',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'AJ',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'BUDGET',
        },
        {
          columnIndex: 'Q',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'R',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'S',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'T',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'U',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'V',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'P',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'S',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'R',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'U',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'T',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'W',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'S',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'P',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Q',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'V',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'W',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'T',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'R',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Q',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'P',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'W',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'V',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'U',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'U',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'V',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'W',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'P',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Q',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'R',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'T',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'W',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'V',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Q',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'P',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'S',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'W',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'T',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'U',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'R',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'S',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'P',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'V',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'U',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'T',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'S',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'R',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Q',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'Y',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Z',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'X',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Z',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'X',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Y',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Z',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'Y',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'X',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'X',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Y',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Z',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'Y',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'X',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'Z',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'X',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'Z',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'Y',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'A',
          rowIndex: '1',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'B',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'C',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'D',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'E',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'F',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'C',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'B',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'E',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'D',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'G',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'C',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'A',
          rowIndex: '3',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'F',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'G',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'D',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'B',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'A',
          rowIndex: '2',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'G',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'F',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'E',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'E',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'F',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'G',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'A',
          rowIndex: '5',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'B',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'D',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'G',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'F',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'A',
          rowIndex: '4',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'C',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'G',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'D',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'E',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'B',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'C',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'F',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'E',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'D',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'C',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'B',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'A',
          rowIndex: '6',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'I',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'J',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'K',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'L',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'M',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'N',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'H',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'K',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'J',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'M',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'L',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'O',
          rowIndex: '6',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'K',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'H',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'I',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'N',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'O',
          rowIndex: '5',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'L',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'J',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'I',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'H',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'O',
          rowIndex: '4',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'N',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'M',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'M',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'N',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'O',
          rowIndex: '3',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'H',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'I',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'J',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'L',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'O',
          rowIndex: '2',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'N',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'I',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'H',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'K',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'O',
          rowIndex: '1',
          itemNumber: 233,
          dataType: null,
        },
        {
          columnIndex: 'L',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'M',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'J',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'K',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'H',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
        {
          columnIndex: 'N',
          rowIndex: '1',
          itemNumber: 233,
          dataType: 'FORECAST',
        },
        {
          columnIndex: 'M',
          rowIndex: '2',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'L',
          rowIndex: '3',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'K',
          rowIndex: '4',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'J',
          rowIndex: '5',
          itemNumber: 233,
          dataType: 'ACTUAL',
        },
        {
          columnIndex: 'I',
          rowIndex: '6',
          itemNumber: 233,
          dataType: 'DYNAMIC_FORECAST',
        },
      ];
      updateDS(dataList);
    }, 2000);
  }, []);

  console.log(tableProps);

  return <FlattenTreeTable {...tableProps} tableHeight={500} />;
};
